# Generated by Django 5.2.7 on 2026-04-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
    ]
