# Generated by Django 6.0 on 2026-04-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_add_soft_delete_to_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatcharea",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="dispatcharea",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
