# Generated by Django 6.0 on 2026-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_dispatcharea_deleted_at_dispatcharea_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_received",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto recibido",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="pending_billing",
            field=models.BooleanField(default=False, verbose_name="Pendiente en caja"),
        ),
    ]
