# Generated by Django 6.0 on 2026-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_pending_billing_and_amount_received"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TARJETA_CREDITO", "Tarjeta Crédito"),
                    ("TARJETA_DEBITO", "Tarjeta Débito"),
                    ("TRANSFERENCIA", "Transferencia"),
                    ("OTRO", "Otro"),
                    ("PENDIENTE", "Pendiente"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
