# Generated by Django 6.0 on 2026-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_change_payment_method_to_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashregister",
            name="total_credito",
        ),
        migrations.AddField(
            model_name="cashregister",
            name="total_otros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="total_pendiente",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="total_tarjeta_credito",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="total_tarjeta_debito",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="total_transferencia",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
