# Generated by Django 5.2.7 on 2026-04-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_add_cashregister_payment_totals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="pending_billing",
        ),
    ]
