# Generated by Django 6.0 on 2026-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_table_pending_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Notas"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de pago"
            ),
        ),
    ]
