# Generated by Django 5.2.7 on 2026-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_productingredient_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la empresa"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RUC"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        help_text="Logo de la empresa para mostrar en comandas (imagen preferiblemente)",
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Eslogan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresa",
            },
        ),
    ]
