# Generated by Django 5.2.7 on 2026-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Stock mínimo"
            ),
        ),
    ]
