# Generated by Django 6.0 on 2026-04-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_invoice_notes_invoice_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Receta de Conversión",
                "verbose_name_plural": "Recetas de Conversión",
            },
        ),
        migrations.CreateModel(
            name="FoodRecipeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_input",
                    models.BooleanField(
                        default=True,
                        help_text="Si marcada = consumo (salida de inventario). Si desmarcada = producto procesado (entrada a inventario).",
                        verbose_name="Es entrada",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.foodrecipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente de Receta",
                "verbose_name_plural": "Ingredientes de Receta",
            },
        ),
    ]
