# Generated by Django 5.2.7 on 2026-04-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_foodrecipe_foodrecipeitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
