# Generated by Django 5.2.7 on 2026-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_add_purchases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="is_active",
        ),
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
