# Generated by Django 5.2.7 on 2026-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_update_supplier_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="order_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de orden"
            ),
        ),
    ]
