# Generated by Django 6.0.4 on 2026-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_purchase_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia Prima'), ('PROCESADO', 'Procesado')], default='MATERIA_PRIMA', max_length=20, verbose_name='Tipo'),
        ),
    ]
