# Generated by Django 6.0.4 on 2026-04-29 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_add_ingredient_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeExecutionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False, verbose_name="Conversión manual"
                    ),
                ),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cantidad producida",
                    ),
                ),
                (
                    "raw_materials_used",
                    models.JSONField(
                        default=list, verbose_name="Materiales consumidos"
                    ),
                ),
                (
                    "products_created",
                    models.JSONField(default=list, verbose_name="Productos creados"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.foodrecipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Conversión",
                "verbose_name_plural": "Reportes de Conversión",
                "ordering": ["-created_at"],
            },
        ),
    ]
